name: serverpod_test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.3.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  serverpod: 2.1.0-beta.2
  meta: ^1.15.0

dev_dependencies:
  serverpod_lints: 2.1.0-beta.2
  test: ^1.24.2

dependency_overrides:
  serverpod:
    path: ../serverpod
  serverpod_lints:
    path: ../serverpod_lints
  serverpod_shared:
    path: ../serverpod_shared
  serverpod_serialization:
    path: ../serverpod_serialization
