# TEMPLATE

name: serverpod_test
version: SERVERPOD_VERSION
description: Severpod test tools to simplify testing of endpoints.
repository: https://github.com/serverpod/serverpod
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod/issues

environment:
  sdk: DART_VERSION

dev_dependencies:
  serverpod_lints: SERVERPOD_VERSION
  test: ^1.24.2
  serverpod: 2.1.0-beta.2
  meta: ^1.15.0

dependency_overrides:
  serverpod:
    path: ../serverpod
  serverpod_lints:
    path: ../serverpod_lints
